name: CI/CD Pipeline - Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**" # Triggers on changes in the backend directory
      - "frontend/**"
      - ".github/workflows/deploy.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------------
      # Build & Push Docker Image
      # -----------------------------------
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: . # Root context of monorepo
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository | lower }}/backend:${{ github.sha }}
      # -----------------------------------
      # Deploy to VPS via SSH
      # -----------------------------------
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Navigate to the app directory
            cd /srv/apps/configurator

            # Create a temporary environment file with the image tag
            echo "IMAGE=ghcr.io/${{ github.repository }}/backend:${{ github.sha }}" > .deploy.env

            # Pull the new image and re-create the container
            docker compose pull
            docker compose up -d

            # Clean up old, unused images
            docker image prune -f
